services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: diack
      MYSQL_DATABASE: QUALITUS
      MYSQL_USER: diack
      MYSQL_PASSWORD: diack
    networks:
      - internalnet
  nodeapp:
    container_name: nodeappcontainer
    image: nodeapp:v1
    build: .
    volumes:
      - .:/usr/code
      - /usr/code/node_modules
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: diack
      DB_PASSWORD: diack
      DB_NAME: QUALITUS
    depends_on:
      - mysqldb
    networks:
      - internalnet
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - mysqldb
    networks:
      - internalnet
volumes:
  database:

networks:
  internalnet:
    driver: bridge
